version: '3.8'
services:
  backend:
    build:
      context: .
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 80
    ports:
      - 8000:80
    volumes:
      - ./app:/api/
    environment:
      - RUTA_MONGO=mongodb://db_mongo:27017/
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=api.diego-luque.com, api.diego-luque.com
      - LETSENCRYPT_HOST=api.diego-luque.com, api.diego-luque.com

# algun network ya creado / any network create already
networks:
  default:
    name: web_private_red_webapps
    external: true

# networks:
#   default:
#     name: database_catalogo-network
#     external: true
